spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: kafkaconsumer
  servelet:
    context-path: /kafkaconsumer
    port: 8080
  kafka:
    topic: topic_madhi
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: group-madhi
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group-madhi
    admin:
      properties:
        bootstrap.servers: 127.0.0.1:9092


